import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import path from "path";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const BRIDGE_FAVICON_SVG_FILE = path.join("images", "favicon.svg");
const BRIDGE_FAVICON_VIRTUAL = "epochgram-bridge-favicon";

const EPOCHGRAM_LOGO_FULL_SVG_FILE = path.join("images", "epochgram-logo-full.svg");
const EPOCHGRAM_LOGO_FULL_VIRTUAL = "epochgram-logo-full";
const BRIDGE_DEFAULT_SETTINGS_YAML_FILE = path.join("src", "plugin", "ai-bridge-page", "settings", "default-bridge-settings.yaml");
const BRIDGE_DEFAULT_SETTINGS_YAML_VIRTUAL = "epochgram-bridge-default-settings-yaml";

const bridgeFaviconInlinePlugin = {
	name: "epochgram-bridge-favicon-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-bridge-favicon$/ }, () => {
			return { path: BRIDGE_FAVICON_VIRTUAL, namespace: "epochgram-bridge-favicon-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-bridge-favicon-inline" }, async () => {
			let svg = "";
			try {
				svg = await fs.promises.readFile(BRIDGE_FAVICON_SVG_FILE, "utf8");
			} catch {
				svg = "";
			}
			return {
				contents: `export default ${JSON.stringify(svg)};`,
				loader: "js",
				watchFiles: [BRIDGE_FAVICON_SVG_FILE]
			};
		});
	}
};

const epochgramLogoFullInlinePlugin = {
	name: "epochgram-logo-full-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-logo-full$/ }, () => {
			return { path: EPOCHGRAM_LOGO_FULL_VIRTUAL, namespace: "epochgram-logo-full-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-logo-full-inline" }, async () => {
			let svg = "";
			try {
				svg = await fs.promises.readFile(EPOCHGRAM_LOGO_FULL_SVG_FILE, "utf8");
			} catch {
				svg = "";
			}
			return {
				contents: `export default ${JSON.stringify(svg)};`,
				loader: "js",
				watchFiles: [EPOCHGRAM_LOGO_FULL_SVG_FILE]
			};
		});
	}
};

const bridgeDefaultSettingsYamlInlinePlugin = {
	name: "epochgram-bridge-default-settings-yaml-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-bridge-default-settings-yaml$/ }, () => {
			return { path: BRIDGE_DEFAULT_SETTINGS_YAML_VIRTUAL, namespace: "epochgram-bridge-default-settings-yaml-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-bridge-default-settings-yaml-inline" }, async () => {
			let yamlText = "";
			try {
				yamlText = await fs.promises.readFile(BRIDGE_DEFAULT_SETTINGS_YAML_FILE, "utf8");
			} catch {
				yamlText = "";
			}
			return {
				contents: `export default ${JSON.stringify(yamlText)};`,
				loader: "js",
				watchFiles: [BRIDGE_DEFAULT_SETTINGS_YAML_FILE]
			};
		});
	}
};



// Some ESM dependencies (e.g., @huggingface/transformers) rely on `import.meta.url`.
// When bundled to CJS, esbuild may otherwise leave this undefined.
// This must be a valid absolute file URL for the current OS.
const importMetaUrlShim = process.platform === "win32"
	? '"file:///C:/epoch/main.js"'
	: '"file:///epoch/main.js"';
const now = new Date();
const pad2 = (n) => String(n).padStart(2, "0");
const buildTimestampStamp =
	`${now.getFullYear()}` +
	`${pad2(now.getMonth() + 1)}` +
	`${pad2(now.getDate())}` +
	`${pad2(now.getHours())}` +
	`${pad2(now.getMinutes())}` +
	`${pad2(now.getSeconds())}`;

const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		"import.meta.url": importMetaUrlShim,
		"__EPOCHGRAM_BUILD_TIMESTAMP__": JSON.stringify(buildTimestampStamp),
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	loader: {
		".wasm": "binary",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [
		// Note: esbuild-plugin-inline-worker@0.1.x takes esbuild BuildOptions directly.
		inlineWorkerPlugin({
			target: "es2020",
			define: {
				// Force browser codepaths inside worker bundles even when Obsidian/Electron exposes `process`.
				// This prevents onnxruntime-web from entering its Node branch (fs/path) inside Web Workers.
				"process.versions.node": "undefined",
				"process.release.name": '""'
			}
		}),
		bridgeFaviconInlinePlugin,
		epochgramLogoFullInlinePlugin,
		bridgeDefaultSettingsYamlInlinePlugin
	],
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await pluginContext.rebuild();
	process.exit(0);
} else {
	await pluginContext.watch();
}
