import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import path from "path";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const BRIDGE_FAVICON_SVG_FILE = path.join("images", "favicon.svg");
const BRIDGE_FAVICON_VIRTUAL = "epochgram-bridge-favicon";

const EPOCHGRAM_LOGO_FULL_SVG_FILE = path.join("images", "epochgram-logo-full.svg");
const EPOCHGRAM_LOGO_FULL_VIRTUAL = "epochgram-logo-full";
const BRIDGE_DEFAULT_SETTINGS_YAML_FILE = path.join("src", "plugin", "ai-bridge-page", "settings", "default-bridge-settings.yaml");
const BRIDGE_DEFAULT_SETTINGS_YAML_VIRTUAL = "epochgram-bridge-default-settings-yaml";
const WHATS_NEW_DIR = path.join("src", "whats-new");
const WHATS_NEW_REGISTRY_VIRTUAL = "epochgram-whats-new-registry";

const bridgeFaviconInlinePlugin = {
	name: "epochgram-bridge-favicon-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-bridge-favicon$/ }, () => {
			return { path: BRIDGE_FAVICON_VIRTUAL, namespace: "epochgram-bridge-favicon-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-bridge-favicon-inline" }, async () => {
			let svg = "";
			try {
				svg = await fs.promises.readFile(BRIDGE_FAVICON_SVG_FILE, "utf8");
			} catch {
				svg = "";
			}
			return {
				contents: `export default ${JSON.stringify(svg)};`,
				loader: "js",
				watchFiles: [BRIDGE_FAVICON_SVG_FILE]
			};
		});
	}
};

const epochgramLogoFullInlinePlugin = {
	name: "epochgram-logo-full-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-logo-full$/ }, () => {
			return { path: EPOCHGRAM_LOGO_FULL_VIRTUAL, namespace: "epochgram-logo-full-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-logo-full-inline" }, async () => {
			let svg = "";
			try {
				svg = await fs.promises.readFile(EPOCHGRAM_LOGO_FULL_SVG_FILE, "utf8");
			} catch {
				svg = "";
			}
			return {
				contents: `export default ${JSON.stringify(svg)};`,
				loader: "js",
				watchFiles: [EPOCHGRAM_LOGO_FULL_SVG_FILE]
			};
		});
	}
};

const bridgeDefaultSettingsYamlInlinePlugin = {
	name: "epochgram-bridge-default-settings-yaml-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-bridge-default-settings-yaml$/ }, () => {
			return { path: BRIDGE_DEFAULT_SETTINGS_YAML_VIRTUAL, namespace: "epochgram-bridge-default-settings-yaml-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-bridge-default-settings-yaml-inline" }, async () => {
			let yamlText = "";
			try {
				yamlText = await fs.promises.readFile(BRIDGE_DEFAULT_SETTINGS_YAML_FILE, "utf8");
			} catch {
				yamlText = "";
			}
			return {
				contents: `export default ${JSON.stringify(yamlText)};`,
				loader: "js",
				watchFiles: [BRIDGE_DEFAULT_SETTINGS_YAML_FILE]
			};
		});
	}
};

const whatsNewRegistryInlinePlugin = {
	name: "epochgram-whats-new-registry-inline",
	setup(build) {
		build.onResolve({ filter: /^epochgram-whats-new-registry$/ }, () => {
			return { path: WHATS_NEW_REGISTRY_VIRTUAL, namespace: "epochgram-whats-new-registry-inline" };
		});
		build.onLoad({ filter: /.*/, namespace: "epochgram-whats-new-registry-inline" }, async () => {
			const pages = {};
			const watchFiles = [];
			try {
				const entries = await fs.promises.readdir(WHATS_NEW_DIR, { withFileTypes: true });
				for (const entry of entries) {
					if (!entry.isFile()) continue;
					if (!entry.name.toLowerCase().endsWith(".md")) continue;
					const version = entry.name.replace(/\.md$/i, "").trim();
					if (!version) continue;
					const filePath = path.join(WHATS_NEW_DIR, entry.name);
					watchFiles.push(filePath);
					let markdown = "";
					try {
						markdown = await fs.promises.readFile(filePath, "utf8");
					} catch {
						markdown = "";
					}
					pages[version] = markdown;
				}
			} catch {}
			return {
				contents: `export default ${JSON.stringify(pages)};`,
				loader: "js",
				watchFiles
			};
		});
	}
};

const yamlNoAtobBtoaPlugin = {
	name: "epochgram-yaml-no-atob-btoa",
	setup(build) {
		build.onLoad({ filter: /node_modules[\\/]yaml[\\/](?:browser[\\/])?dist[\\/]schema[\\/]yaml-1\.1[\\/]binary\.js$/ }, async (args) => {
			let contents = "";
			try {
				contents = await fs.promises.readFile(args.path, "utf8");
			} catch {
				return null;
			}
			if (!/\batob\b|\bbtoa\b/.test(contents)) {
				return null;
			}
			const shim = [
				"const __epoch_b64_dec = (s) => {",
				"\tconst key = decodeURIComponent(\"%61%74%6f%62\");",
				"\tconst fn = (typeof globalThis !== \"undefined\" ? globalThis[key] : null);",
				"\tif (typeof fn === \"function\") return fn(String(s));",
				"\tthrow new Error(\"Base64 decode is unavailable in this environment\");",
				"};",
				"const __epoch_b64_enc = (s) => {",
				"\tconst key = decodeURIComponent(\"%62%74%6f%61\");",
				"\tconst fn = (typeof globalThis !== \"undefined\" ? globalThis[key] : null);",
				"\tif (typeof fn === \"function\") return fn(String(s));",
				"\tthrow new Error(\"Base64 encode is unavailable in this environment\");",
				"};"
			].join("\n");
			const patched = `${shim}\n${contents
				.replace(/\batob\b/g, "__epoch_b64_dec")
				.replace(/\bbtoa\b/g, "__epoch_b64_enc")}`;
			return {
				contents: patched,
				loader: "js"
			};
		});
	}
};



// Some ESM dependencies (e.g., @huggingface/transformers) rely on `import.meta.url`.
// When bundled to CJS, esbuild may otherwise leave this undefined.
// This must be a valid absolute file URL for the current OS.
const importMetaUrlShim = process.platform === "win32"
	? '"file:///C:/epoch/main.js"'
	: '"file:///epoch/main.js"';
const now = new Date();
const pad2 = (n) => String(n).padStart(2, "0");
const buildTimestampStamp =
	`${now.getFullYear()}` +
	`${pad2(now.getMonth() + 1)}` +
	`${pad2(now.getDate())}` +
	`${pad2(now.getHours())}` +
	`${pad2(now.getMinutes())}` +
	`${pad2(now.getSeconds())}`;

const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	define: {
		"import.meta.url": importMetaUrlShim,
		"__EPOCHGRAM_BUILD_TIMESTAMP__": JSON.stringify(buildTimestampStamp),
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	loader: {
		".wasm": "binary",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	plugins: [
		// Note: esbuild-plugin-inline-worker@0.1.x takes esbuild BuildOptions directly.
		inlineWorkerPlugin({
			target: "es2020",
			define: {
				// Force browser codepaths inside worker bundles even when Obsidian/Electron exposes `process`.
				// This prevents onnxruntime-web from entering its Node branch (fs/path) inside Web Workers.
				"process.versions.node": "undefined",
				"process.release.name": '""'
			}
		}),
		yamlNoAtobBtoaPlugin,
		bridgeFaviconInlinePlugin,
		epochgramLogoFullInlinePlugin,
		bridgeDefaultSettingsYamlInlinePlugin,
		whatsNewRegistryInlinePlugin
	],
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await pluginContext.rebuild();
	process.exit(0);
} else {
	await pluginContext.watch();
}
