import type { DateEntry } from "../../indexer/types";
import type { EpochCanvas } from "../epoch-canvas";
import type { DayLayout, HoverOverlay } from "../epoch-canvas-types";
import type { CanvasIconCache } from "../canvas-icon-cache";

export interface CanvasDrawState {
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    root: HTMLElement;
    scale: number;
    offsetY: number;
    targetScale: number;
    targetOffsetY: number;
    index: Record<string, DateEntry[]>;
    layouts: DayLayout[];
    lastVisibleEntryCount: number | null;
    hoverOverlay: HoverOverlay | null;
    hoverAnim: number;
    hoverTarget?: number;
    animSummary: { dayIndex: number; itemIndex: number } | null;
    prevAnimSummary?: { dayIndex: number; itemIndex: number } | null;
    outgoingSummaries?: Array<{ dayIndex: number; itemIndex: number; t: number }> | null;
    outgoingDates?: Array<{ index: number; t: number }> | null;
    animDateIndex: number | null;
    animatingView?: boolean;
    velocityY?: number;
    viewInteractionUntil?: number;
    iconCache: CanvasIconCache;
    showHidden: boolean;
    showAttachments: boolean;
    showTrackedChanges: boolean;
    showContentDates: boolean;
    showDraftOnly?: boolean;
    showPropDates?: boolean;
    epochsView?: boolean;
    activeFilePath: string | null;
    focusedEpochRange?: { start: string; end: string } | null;
    semanticRelatedPaths?: Set<string> | null;
    semanticRelatedTermPaths?: Set<string> | null;
    semanticRelatedActiveTerm?: string | null;
    keepHoverAfterMenu?: boolean;
    __touchHoverPinnedUntil?: number;
    pendingVisibilityDraw: boolean;
    visibilityRetryTimeout: number | null;
    suppressNextFocusHover: string | null;
    forceNextFocusHover: string | null;
    searchQuery?: string;
    pathsWithEmbeddingTerm?: Set<string> | null;
    pathsWithClassifiedTerm?: Set<string> | null;
    wrapFadeCache?: Map<string, unknown>;
    packAnimating?: boolean;
    __ellipsisNowLast?: number;
    __ellipsisPrevAnimatingView?: boolean;
    __ellipsisSettleUntil?: number;
    __globalDenseMode?: boolean;
    __globalCompactMode?: boolean;
    epochPackAlphaByIndex?: Map<number, number> | null;
    epochPackCenterCache?: Map<number, {
        offset: number;
        lastAt: number;
        appearAt: number;
        moveUntil?: number;
        height?: number;
    }>;
    __epochPackSig?: string;
    __epochIndexCacheRef?: Record<string, DateEntry[]>;
    __epochIndexCacheTodayKey?: string;
    __epochIndexCacheByBucket?: Map<string, number[]>;
    __entryIndexCacheRef?: Record<string, DateEntry[]>;
    __entryIndexCacheTodayKey?: string;
    __entryIndexCacheFilterKey?: string;
    __entryIndexCacheAll?: number[];
    __epochPackInstantAppearOnce?: boolean;
    __epochPackBaselineShift?: number;
    __epochPackBaselineShiftTarget?: number;
    __epochPackBaselineShiftMoveUntil?: number;
    __epochPackBaselineShiftLastAt?: number;
    __epochPackBaselineAnchorIndex?: number | null;
    __epochPackBaselineAnchorLockUntil?: number;
    epochPackLastScale?: number;
    epochPackZoomUntil?: number;
    epochPackBucketAnimating?: boolean;
    inheritedMarkSourceByPath?: Map<string, string> | null;
    plugin: {
        settings: {
            enableAnimation?: boolean;
            generateEpochs?: boolean;
            filenameWordsCount?: number;
            summaryWordsCount?: number;
            compactModeMinWidthPercent?: number;
        };
        __epochInheritedMarkIndexByPath?: Map<string, number> | null;
        __epochInheritedMarkSourceByPath?: Map<string, string> | null;
    };
    scheduleVisibilityCheck(): void;
    scaleFont(font: string, factor: number): string;
    getCssValue(css: CSSStyleDeclaration, property: string): string;
    getToday(): Date;
    getDateForIndex(index: number, today: Date): Date;
    getEntryTitle(entry: DateEntry): string;
    focusFile(filePath: string, line: number | null, useHoverHighlight: boolean): boolean;
    processPendingScrollNavHighlight(): void;
    requestHoverAnimation(): void;
}

export function getDrawState(canvas: EpochCanvas): CanvasDrawState {
    return canvas as unknown as CanvasDrawState;
}
